#!/usr/bin/env python3
"""Generates source/cacerts.h: the root certificates the Weather app trusts, as one NUL-terminated PEM string.

Usage: python3 tools/gencerts.py [path/to/ca-bundle.pem]     (default: the system bundle)

Only the roots listed in WANTED are embedded (public roots used by Let's Encrypt, Google Trust Services/Cloudflare, DigiCert,
Sectigo/USERTrust, Amazon and GlobalSign; roots the current Mozilla store no longer carries are left out), so that the TLS check is a real one but the table stays small (~20 KB).
Add a name to WANTED and re-run if a provider changes its root. The script fails if a wanted root is missing from the bundle.
"""
import re, subprocess, sys, hashlib, os

WANTED = [
    "ISRG Root X1", "ISRG Root X2",
    "GTS Root R1", "GTS Root R3", "GTS Root R4",
    "DigiCert Global Root G2", "DigiCert Global Root G3", "DigiCert TLS ECC P384 Root G5", "DigiCert TLS RSA4096 Root G5",
    "USERTrust RSA Certification Authority", "USERTrust ECC Certification Authority",
    "Amazon Root CA 1", "Amazon Root CA 2", "Amazon Root CA 3", "Amazon Root CA 4",
    "GlobalSign Root R46", "GlobalSign Root E46",
]

bundle = sys.argv[1] if len(sys.argv) > 1 else "/etc/ssl/certs/ca-certificates.crt"
text = open(bundle).read()
pems = re.findall(r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----", text, re.S)
found = {}
for pem in pems:
    out = subprocess.run(["openssl", "x509", "-noout", "-subject", "-nameopt", "multiline,-esc_msb"], input=pem.encode(), capture_output=True).stdout.decode("utf-8", "replace")
    m = re.search(r"commonName\s*=\s*(.+)", out)
    cn = m.group(1).strip() if m else ""
    if cn in WANTED and cn not in found:
        found[cn] = pem
missing = [w for w in WANTED if w not in found]
if missing:
    print("missing from bundle:", ", ".join(missing), file=sys.stderr)
    sys.exit(1)

lines = ["// Generated by weather/tools/gencerts.py - do not edit.", "// Roots: " + "; ".join(WANTED), "#pragma once", "", "static const char CA_BUNDLE_PEM[] ="]
total = 0
for cn in WANTED:
    lines.append("\t// " + cn)
    for ln in found[cn].strip().splitlines():
        lines.append('\t"%s\\n"' % ln)
        total += len(ln) + 1
lines[-1] += ";"
lines.append("static const unsigned CA_BUNDLE_COUNT = %d;" % len(WANTED))
open(os.path.join(os.path.dirname(__file__), "..", "source", "cacerts.h"), "w").write("\n".join(lines) + "\n")
print("wrote cacerts.h: %d roots, %d bytes of PEM" % (len(WANTED), total))
